# Generated by Django 5.1 on 2024-09-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_country_options_alter_creator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='images', to='viewer.creator')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='viewer.movie')),
            ],
        ),
    ]
